// Generated by jextract

package dev.viskar.lib.dinput8.natives;

import jdk.incubator.foreign.*;

class dinput_h_constants_0 {

    /* package-private */ dinput_h_constants_0() {
    }

    static final LibraryLookup[] LIBRARIES = RuntimeHelper.libraries(new String[]{
            "C:\\Windows\\System32\\dinput8.dll",
            "C:\\Windows\\System32\\dinput.dll"
    });

    static final int DIRECTINPUT_HEADER_VERSION() {
        return (int) 2048L;
    }

    static final int DIEFT_ALL() {
        return (int) 0L;
    }

    static final int DIEFT_CONSTANTFORCE() {
        return (int) 1L;
    }

    static final int DIEFT_RAMPFORCE() {
        return (int) 2L;
    }

    static final int DIEFT_PERIODIC() {
        return (int) 3L;
    }

    static final int DIEFT_CONDITION() {
        return (int) 4L;
    }

    static final int DIEFT_CUSTOMFORCE() {
        return (int) 5L;
    }

    static final int DIEFT_HARDWARE() {
        return (int) 255L;
    }

    static final int DIEFT_FFATTACK() {
        return (int) 512L;
    }

    static final int DIEFT_FFFADE() {
        return (int) 1024L;
    }

    static final int DIEFT_SATURATION() {
        return (int) 2048L;
    }

    static final int DIEFT_POSNEGCOEFFICIENTS() {
        return (int) 4096L;
    }

    static final int DIEFT_POSNEGSATURATION() {
        return (int) 8192L;
    }

    static final int DIEFT_DEADBAND() {
        return (int) 16384L;
    }

    static final int DIEFT_STARTDELAY() {
        return (int) 32768L;
    }

    static final int DI_DEGREES() {
        return (int) 100L;
    }

    static final int DI_FFNOMINALMAX() {
        return (int) 10000L;
    }

    static final int DI_SECONDS() {
        return (int) 1000000L;
    }

    static final int DIEFF_OBJECTIDS() {
        return (int) 1L;
    }

    static final int DIEFF_OBJECTOFFSETS() {
        return (int) 2L;
    }

    static final int DIEFF_CARTESIAN() {
        return (int) 16L;
    }

    static final int DIEFF_POLAR() {
        return (int) 32L;
    }

    static final int DIEFF_SPHERICAL() {
        return (int) 64L;
    }

    static final int DIEP_DURATION() {
        return (int) 1L;
    }

    static final int DIEP_SAMPLEPERIOD() {
        return (int) 2L;
    }

    static final int DIEP_GAIN() {
        return (int) 4L;
    }

    static final int DIEP_TRIGGERBUTTON() {
        return (int) 8L;
    }

    static final int DIEP_TRIGGERREPEATINTERVAL() {
        return (int) 16L;
    }

    static final int DIEP_AXES() {
        return (int) 32L;
    }

    static final int DIEP_DIRECTION() {
        return (int) 64L;
    }

    static final int DIEP_ENVELOPE() {
        return (int) 128L;
    }

    static final int DIEP_TYPESPECIFICPARAMS() {
        return (int) 256L;
    }

    static final int DIEP_STARTDELAY() {
        return (int) 512L;
    }

    static final int DIEP_ALLPARAMS_DX5() {
        return (int) 511L;
    }

    static final int DIEP_ALLPARAMS() {
        return (int) 1023L;
    }

    static final int DIEP_START() {
        return (int) 536870912L;
    }

    static final int DIEP_NORESTART() {
        return (int) 1073741824L;
    }

    static final int DIES_SOLO() {
        return (int) 1L;
    }

    static final int DIEGES_PLAYING() {
        return (int) 1L;
    }

    static final int DIEGES_EMULATED() {
        return (int) 2L;
    }

    static final int DI8DEVCLASS_ALL() {
        return (int) 0L;
    }

    static final int DI8DEVCLASS_DEVICE() {
        return (int) 1L;
    }

    static final int DI8DEVCLASS_POINTER() {
        return (int) 2L;
    }

    static final int DI8DEVCLASS_KEYBOARD() {
        return (int) 3L;
    }

    static final int DI8DEVCLASS_GAMECTRL() {
        return (int) 4L;
    }

    static final int DI8DEVTYPE_DEVICE() {
        return (int) 17L;
    }

    static final int DI8DEVTYPE_MOUSE() {
        return (int) 18L;
    }

    static final int DI8DEVTYPE_KEYBOARD() {
        return (int) 19L;
    }

    static final int DI8DEVTYPE_JOYSTICK() {
        return (int) 20L;
    }

    static final int DI8DEVTYPE_GAMEPAD() {
        return (int) 21L;
    }

    static final int DI8DEVTYPE_DRIVING() {
        return (int) 22L;
    }

    static final int DI8DEVTYPE_FLIGHT() {
        return (int) 23L;
    }

    static final int DI8DEVTYPE_1STPERSON() {
        return (int) 24L;
    }

    static final int DI8DEVTYPE_DEVICECTRL() {
        return (int) 25L;
    }

    static final int DI8DEVTYPE_SCREENPOINTER() {
        return (int) 26L;
    }

    static final int DI8DEVTYPE_REMOTE() {
        return (int) 27L;
    }

    static final int DI8DEVTYPE_SUPPLEMENTAL() {
        return (int) 28L;
    }

    static final int DIDEVTYPE_HID() {
        return (int) 65536L;
    }

    static final int DI8DEVTYPEMOUSE_UNKNOWN() {
        return (int) 1L;
    }

    static final int DI8DEVTYPEMOUSE_TRADITIONAL() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEMOUSE_FINGERSTICK() {
        return (int) 3L;
    }

    static final int DI8DEVTYPEMOUSE_TOUCHPAD() {
        return (int) 4L;
    }

    static final int DI8DEVTYPEMOUSE_TRACKBALL() {
        return (int) 5L;
    }

    static final int DI8DEVTYPEMOUSE_ABSOLUTE() {
        return (int) 6L;
    }

    static final int DI8DEVTYPEKEYBOARD_UNKNOWN() {
        return (int) 0L;
    }

    static final int DI8DEVTYPEKEYBOARD_PCXT() {
        return (int) 1L;
    }

    static final int DI8DEVTYPEKEYBOARD_OLIVETTI() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEKEYBOARD_PCAT() {
        return (int) 3L;
    }

    static final int DI8DEVTYPEKEYBOARD_PCENH() {
        return (int) 4L;
    }

    static final int DI8DEVTYPEKEYBOARD_NOKIA1050() {
        return (int) 5L;
    }

    static final int DI8DEVTYPEKEYBOARD_NOKIA9140() {
        return (int) 6L;
    }

    static final int DI8DEVTYPEKEYBOARD_NEC98() {
        return (int) 7L;
    }

    static final int DI8DEVTYPEKEYBOARD_NEC98LAPTOP() {
        return (int) 8L;
    }

    static final int DI8DEVTYPEKEYBOARD_NEC98106() {
        return (int) 9L;
    }

    static final int DI8DEVTYPEKEYBOARD_JAPAN106() {
        return (int) 10L;
    }

    static final int DI8DEVTYPEKEYBOARD_JAPANAX() {
        return (int) 11L;
    }

    static final int DI8DEVTYPEKEYBOARD_J3100() {
        return (int) 12L;
    }

    static final int DI8DEVTYPE_LIMITEDGAMESUBTYPE() {
        return (int) 1L;
    }

    static final int DI8DEVTYPEJOYSTICK_STANDARD() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEGAMEPAD_STANDARD() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEGAMEPAD_TILT() {
        return (int) 3L;
    }

    static final int DI8DEVTYPEDRIVING_COMBINEDPEDALS() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEDRIVING_DUALPEDALS() {
        return (int) 3L;
    }

    static final int DI8DEVTYPEDRIVING_THREEPEDALS() {
        return (int) 4L;
    }

    static final int DI8DEVTYPEDRIVING_HANDHELD() {
        return (int) 5L;
    }

    static final int DI8DEVTYPEFLIGHT_STICK() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEFLIGHT_YOKE() {
        return (int) 3L;
    }

    static final int DI8DEVTYPEFLIGHT_RC() {
        return (int) 4L;
    }

    static final int DI8DEVTYPE1STPERSON_UNKNOWN() {
        return (int) 2L;
    }

    static final int DI8DEVTYPE1STPERSON_SIXDOF() {
        return (int) 3L;
    }

    static final int DI8DEVTYPE1STPERSON_SHOOTER() {
        return (int) 4L;
    }

    static final int DI8DEVTYPESCREENPTR_UNKNOWN() {
        return (int) 2L;
    }

    static final int DI8DEVTYPESCREENPTR_LIGHTGUN() {
        return (int) 3L;
    }

    static final int DI8DEVTYPESCREENPTR_LIGHTPEN() {
        return (int) 4L;
    }

    static final int DI8DEVTYPESCREENPTR_TOUCH() {
        return (int) 5L;
    }

    static final int DI8DEVTYPEREMOTE_UNKNOWN() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEDEVICECTRL_UNKNOWN() {
        return (int) 2L;
    }

    static final int DI8DEVTYPEDEVICECTRL_COMMSSELECTION() {
        return (int) 3L;
    }

    static final int DI8DEVTYPEDEVICECTRL_COMMSSELECTION_HARDWIRED() {
        return (int) 4L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_UNKNOWN() {
        return (int) 2L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_2NDHANDCONTROLLER() {
        return (int) 3L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_HEADTRACKER() {
        return (int) 4L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_HANDTRACKER() {
        return (int) 5L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_SHIFTSTICKGATE() {
        return (int) 6L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_SHIFTER() {
        return (int) 7L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_THROTTLE() {
        return (int) 8L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_SPLITTHROTTLE() {
        return (int) 9L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_COMBINEDPEDALS() {
        return (int) 10L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_DUALPEDALS() {
        return (int) 11L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_THREEPEDALS() {
        return (int) 12L;
    }

    static final int DI8DEVTYPESUPPLEMENTAL_RUDDERPEDALS() {
        return (int) 13L;
    }

    static final int DIDC_ATTACHED() {
        return (int) 1L;
    }

    static final int DIDC_POLLEDDEVICE() {
        return (int) 2L;
    }

    static final int DIDC_EMULATED() {
        return (int) 4L;
    }

    static final int DIDC_POLLEDDATAFORMAT() {
        return (int) 8L;
    }

    static final int DIDC_FORCEFEEDBACK() {
        return (int) 256L;
    }

    static final int DIDC_FFATTACK() {
        return (int) 512L;
    }

    static final int DIDC_FFFADE() {
        return (int) 1024L;
    }

    static final int DIDC_SATURATION() {
        return (int) 2048L;
    }

    static final int DIDC_POSNEGCOEFFICIENTS() {
        return (int) 4096L;
    }

    static final int DIDC_POSNEGSATURATION() {
        return (int) 8192L;
    }

    static final int DIDC_DEADBAND() {
        return (int) 16384L;
    }

    static final int DIDC_STARTDELAY() {
        return (int) 32768L;
    }

    static final int DIDC_ALIAS() {
        return (int) 65536L;
    }

    static final int DIDC_PHANTOM() {
        return (int) 131072L;
    }

    static final int DIDC_HIDDEN() {
        return (int) 262144L;
    }

    static final int DIDFT_ALL() {
        return (int) 0L;
    }

    static final int DIDFT_RELAXIS() {
        return (int) 1L;
    }

    static final int DIDFT_ABSAXIS() {
        return (int) 2L;
    }

    static final int DIDFT_AXIS() {
        return (int) 3L;
    }

    static final int DIDFT_PSHBUTTON() {
        return (int) 4L;
    }

    static final int DIDFT_TGLBUTTON() {
        return (int) 8L;
    }

    static final int DIDFT_BUTTON() {
        return (int) 12L;
    }

    static final int DIDFT_POV() {
        return (int) 16L;
    }

    static final int DIDFT_COLLECTION() {
        return (int) 64L;
    }

    static final int DIDFT_NODATA() {
        return (int) 128L;
    }

    static final int DIDFT_ANYINSTANCE() {
        return (int) 16776960L;
    }

    static final int DIDFT_FFACTUATOR() {
        return (int) 16777216L;
    }

    static final int DIDFT_FFEFFECTTRIGGER() {
        return (int) 33554432L;
    }

    static final int DIDFT_OUTPUT() {
        return (int) 268435456L;
    }

    static final int DIDFT_VENDORDEFINED() {
        return (int) 67108864L;
    }

    static final int DIDFT_ALIAS() {
        return (int) 134217728L;
    }

    static final int DIDFT_NOCOLLECTION() {
        return (int) 16776960L;
    }

    static final int DIDF_ABSAXIS() {
        return (int) 1L;
    }

    static final int DIDF_RELAXIS() {
        return (int) 2L;
    }

    static final int DIA_FORCEFEEDBACK() {
        return (int) 1L;
    }

    static final int DIA_APPMAPPED() {
        return (int) 2L;
    }

    static final int DIA_APPNOMAP() {
        return (int) 4L;
    }

    static final int DIA_NORANGE() {
        return (int) 8L;
    }

    static final int DIA_APPFIXED() {
        return (int) 16L;
    }

    static final int DIAH_UNMAPPED() {
        return (int) 0L;
    }

    static final int DIAH_USERCONFIG() {
        return (int) 1L;
    }

    static final int DIAH_APPREQUESTED() {
        return (int) 2L;
    }

    static final int DIAH_HWAPP() {
        return (int) 4L;
    }

    static final int DIAH_HWDEFAULT() {
        return (int) 8L;
    }

    static final int DIAH_DEFAULT() {
        return (int) 32L;
    }

    static final int DIAFTS_UNUSEDDEVICELOW() {
        return (int) 0L;
    }

    static final int DIAFTS_UNUSEDDEVICEHIGH() {
        return (int) 0L;
    }

    static final int DIDBAM_DEFAULT() {
        return (int) 0L;
    }

    static final int DIDBAM_PRESERVE() {
        return (int) 1L;
    }

    static final int DIDBAM_INITIALIZE() {
        return (int) 2L;
    }

    static final int DIDBAM_HWDEFAULTS() {
        return (int) 4L;
    }

    static final int DIDSAM_DEFAULT() {
        return (int) 0L;
    }

    static final int DIDSAM_NOUSER() {
        return (int) 1L;
    }

    static final int DIDSAM_FORCESAVE() {
        return (int) 2L;
    }

    static final int DICD_DEFAULT() {
        return (int) 0L;
    }

    static final int DICD_EDIT() {
        return (int) 1L;
    }

    static final int DIDIFT_CONFIGURATION() {
        return (int) 1L;
    }

    static final int DIDIFT_OVERLAY() {
        return (int) 2L;
    }

    static final int DIDAL_CENTERED() {
        return (int) 0L;
    }

    static final int DIDAL_LEFTALIGNED() {
        return (int) 1L;
    }

    static final int DIDAL_RIGHTALIGNED() {
        return (int) 2L;
    }

    static final int DIDAL_MIDDLE() {
        return (int) 0L;
    }

    static final int DIDAL_TOPALIGNED() {
        return (int) 4L;
    }

    static final int DIDAL_BOTTOMALIGNED() {
        return (int) 8L;
    }

    static final int DIDOI_FFACTUATOR() {
        return (int) 1L;
    }

    static final int DIDOI_FFEFFECTTRIGGER() {
        return (int) 2L;
    }

    static final int DIDOI_POLLED() {
        return (int) 32768L;
    }

    static final int DIDOI_ASPECTPOSITION() {
        return (int) 256L;
    }

    static final int DIDOI_ASPECTVELOCITY() {
        return (int) 512L;
    }

    static final int DIDOI_ASPECTACCEL() {
        return (int) 768L;
    }

    static final int DIDOI_ASPECTFORCE() {
        return (int) 1024L;
    }

    static final int DIDOI_ASPECTMASK() {
        return (int) 3840L;
    }

    static final int DIDOI_GUIDISUSAGE() {
        return (int) 65536L;
    }

    static final int DIPH_DEVICE() {
        return (int) 0L;
    }

    static final int DIPH_BYOFFSET() {
        return (int) 1L;
    }

    static final int DIPH_BYID() {
        return (int) 2L;
    }

    static final int DIPH_BYUSAGE() {
        return (int) 3L;
    }

    static final int MAXCPOINTSNUM() {
        return (int) 8L;
    }

    static final int DIPROPAXISMODE_ABS() {
        return (int) 0L;
    }

    static final int DIPROPAXISMODE_REL() {
        return (int) 1L;
    }

    static final int DIPROPAUTOCENTER_OFF() {
        return (int) 0L;
    }

    static final int DIPROPAUTOCENTER_ON() {
        return (int) 1L;
    }

    static final int DIPROPCALIBRATIONMODE_COOKED() {
        return (int) 0L;
    }

    static final int DIPROPCALIBRATIONMODE_RAW() {
        return (int) 1L;
    }

    static final int DIGDD_PEEK() {
        return (int) 1L;
    }

    static final int DISCL_EXCLUSIVE() {
        return (int) 1L;
    }

    static final int DISCL_NONEXCLUSIVE() {
        return (int) 2L;
    }

    static final int DISCL_FOREGROUND() {
        return (int) 4L;
    }

    static final int DISCL_BACKGROUND() {
        return (int) 8L;
    }

    static final int DISCL_NOWINKEY() {
        return (int) 16L;
    }

    static final int DISFFC_RESET() {
        return (int) 1L;
    }

    static final int DISFFC_STOPALL() {
        return (int) 2L;
    }

    static final int DISFFC_PAUSE() {
        return (int) 4L;
    }

    static final int DISFFC_CONTINUE() {
        return (int) 8L;
    }

    static final int DISFFC_SETACTUATORSON() {
        return (int) 16L;
    }

    static final int DISFFC_SETACTUATORSOFF() {
        return (int) 32L;
    }

    static final int DIGFFS_EMPTY() {
        return (int) 1L;
    }

    static final int DIGFFS_STOPPED() {
        return (int) 2L;
    }

    static final int DIGFFS_PAUSED() {
        return (int) 4L;
    }

    static final int DIGFFS_ACTUATORSON() {
        return (int) 16L;
    }

    static final int DIGFFS_ACTUATORSOFF() {
        return (int) 32L;
    }

    static final int DIGFFS_POWERON() {
        return (int) 64L;
    }

    static final int DIGFFS_POWEROFF() {
        return (int) 128L;
    }

    static final int DIGFFS_SAFETYSWITCHON() {
        return (int) 256L;
    }

    static final int DIGFFS_SAFETYSWITCHOFF() {
        return (int) 512L;
    }

    static final int DIGFFS_USERFFSWITCHON() {
        return (int) 1024L;
    }

    static final int DIGFFS_USERFFSWITCHOFF() {
        return (int) 2048L;
    }

    static final int DISDD_CONTINUE() {
        return (int) 1L;
    }

    static final int DIFEF_DEFAULT() {
        return (int) 0L;
    }

    static final int DIFEF_INCLUDENONSTANDARD() {
        return (int) 1L;
    }

    static final int DIFEF_MODIFYIFNEEDED() {
        return (int) 16L;
    }

    static final int DIK_ESCAPE() {
        return (int) 1L;
    }

    static final int DIK_1() {
        return (int) 2L;
    }

    static final int DIK_2() {
        return (int) 3L;
    }

    static final int DIK_3() {
        return (int) 4L;
    }

    static final int DIK_4() {
        return (int) 5L;
    }

    static final int DIK_5() {
        return (int) 6L;
    }

    static final int DIK_6() {
        return (int) 7L;
    }

    static final int DIK_7() {
        return (int) 8L;
    }

    static final int DIK_8() {
        return (int) 9L;
    }

    static final int DIK_9() {
        return (int) 10L;
    }

    static final int DIK_0() {
        return (int) 11L;
    }

    static final int DIK_MINUS() {
        return (int) 12L;
    }

    static final int DIK_EQUALS() {
        return (int) 13L;
    }

    static final int DIK_BACK() {
        return (int) 14L;
    }

    static final int DIK_TAB() {
        return (int) 15L;
    }

    static final int DIK_Q() {
        return (int) 16L;
    }

    static final int DIK_W() {
        return (int) 17L;
    }

    static final int DIK_E() {
        return (int) 18L;
    }

    static final int DIK_R() {
        return (int) 19L;
    }

    static final int DIK_T() {
        return (int) 20L;
    }

    static final int DIK_Y() {
        return (int) 21L;
    }

    static final int DIK_U() {
        return (int) 22L;
    }

    static final int DIK_I() {
        return (int) 23L;
    }

    static final int DIK_O() {
        return (int) 24L;
    }

    static final int DIK_P() {
        return (int) 25L;
    }

    static final int DIK_LBRACKET() {
        return (int) 26L;
    }

    static final int DIK_RBRACKET() {
        return (int) 27L;
    }

    static final int DIK_RETURN() {
        return (int) 28L;
    }

    static final int DIK_LCONTROL() {
        return (int) 29L;
    }

    static final int DIK_A() {
        return (int) 30L;
    }

    static final int DIK_S() {
        return (int) 31L;
    }

    static final int DIK_D() {
        return (int) 32L;
    }

    static final int DIK_F() {
        return (int) 33L;
    }

    static final int DIK_G() {
        return (int) 34L;
    }

    static final int DIK_H() {
        return (int) 35L;
    }

    static final int DIK_J() {
        return (int) 36L;
    }

    static final int DIK_K() {
        return (int) 37L;
    }

    static final int DIK_L() {
        return (int) 38L;
    }

    static final int DIK_SEMICOLON() {
        return (int) 39L;
    }

    static final int DIK_APOSTROPHE() {
        return (int) 40L;
    }

    static final int DIK_GRAVE() {
        return (int) 41L;
    }

    static final int DIK_LSHIFT() {
        return (int) 42L;
    }

    static final int DIK_BACKSLASH() {
        return (int) 43L;
    }

    static final int DIK_Z() {
        return (int) 44L;
    }

    static final int DIK_X() {
        return (int) 45L;
    }

    static final int DIK_C() {
        return (int) 46L;
    }

    static final int DIK_V() {
        return (int) 47L;
    }

    static final int DIK_B() {
        return (int) 48L;
    }

    static final int DIK_N() {
        return (int) 49L;
    }

    static final int DIK_M() {
        return (int) 50L;
    }

    static final int DIK_COMMA() {
        return (int) 51L;
    }

    static final int DIK_PERIOD() {
        return (int) 52L;
    }

    static final int DIK_SLASH() {
        return (int) 53L;
    }

    static final int DIK_RSHIFT() {
        return (int) 54L;
    }

    static final int DIK_MULTIPLY() {
        return (int) 55L;
    }

    static final int DIK_LMENU() {
        return (int) 56L;
    }

    static final int DIK_SPACE() {
        return (int) 57L;
    }

    static final int DIK_CAPITAL() {
        return (int) 58L;
    }

    static final int DIK_F1() {
        return (int) 59L;
    }

    static final int DIK_F2() {
        return (int) 60L;
    }

    static final int DIK_F3() {
        return (int) 61L;
    }

    static final int DIK_F4() {
        return (int) 62L;
    }

    static final int DIK_F5() {
        return (int) 63L;
    }

    static final int DIK_F6() {
        return (int) 64L;
    }

    static final int DIK_F7() {
        return (int) 65L;
    }

    static final int DIK_F8() {
        return (int) 66L;
    }

    static final int DIK_F9() {
        return (int) 67L;
    }

    static final int DIK_F10() {
        return (int) 68L;
    }

    static final int DIK_NUMLOCK() {
        return (int) 69L;
    }

    static final int DIK_SCROLL() {
        return (int) 70L;
    }

    static final int DIK_NUMPAD7() {
        return (int) 71L;
    }

    static final int DIK_NUMPAD8() {
        return (int) 72L;
    }

    static final int DIK_NUMPAD9() {
        return (int) 73L;
    }

    static final int DIK_SUBTRACT() {
        return (int) 74L;
    }

    static final int DIK_NUMPAD4() {
        return (int) 75L;
    }

    static final int DIK_NUMPAD5() {
        return (int) 76L;
    }

    static final int DIK_NUMPAD6() {
        return (int) 77L;
    }

    static final int DIK_ADD() {
        return (int) 78L;
    }

    static final int DIK_NUMPAD1() {
        return (int) 79L;
    }

    static final int DIK_NUMPAD2() {
        return (int) 80L;
    }

    static final int DIK_NUMPAD3() {
        return (int) 81L;
    }

    static final int DIK_NUMPAD0() {
        return (int) 82L;
    }

    static final int DIK_DECIMAL() {
        return (int) 83L;
    }

    static final int DIK_OEM_102() {
        return (int) 86L;
    }

    static final int DIK_F11() {
        return (int) 87L;
    }

    static final int DIK_F12() {
        return (int) 88L;
    }

    static final int DIK_F13() {
        return (int) 100L;
    }

    static final int DIK_F14() {
        return (int) 101L;
    }

    static final int DIK_F15() {
        return (int) 102L;
    }

    static final int DIK_KANA() {
        return (int) 112L;
    }

    static final int DIK_ABNT_C1() {
        return (int) 115L;
    }

    static final int DIK_CONVERT() {
        return (int) 121L;
    }

    static final int DIK_NOCONVERT() {
        return (int) 123L;
    }

    static final int DIK_YEN() {
        return (int) 125L;
    }

    static final int DIK_ABNT_C2() {
        return (int) 126L;
    }

    static final int DIK_NUMPADEQUALS() {
        return (int) 141L;
    }

    static final int DIK_PREVTRACK() {
        return (int) 144L;
    }

    static final int DIK_AT() {
        return (int) 145L;
    }

    static final int DIK_COLON() {
        return (int) 146L;
    }

    static final int DIK_UNDERLINE() {
        return (int) 147L;
    }

    static final int DIK_KANJI() {
        return (int) 148L;
    }

    static final int DIK_STOP() {
        return (int) 149L;
    }

    static final int DIK_AX() {
        return (int) 150L;
    }

    static final int DIK_UNLABELED() {
        return (int) 151L;
    }

    static final int DIK_NEXTTRACK() {
        return (int) 153L;
    }

    static final int DIK_NUMPADENTER() {
        return (int) 156L;
    }

    static final int DIK_RCONTROL() {
        return (int) 157L;
    }

    static final int DIK_MUTE() {
        return (int) 160L;
    }

    static final int DIK_CALCULATOR() {
        return (int) 161L;
    }

    static final int DIK_PLAYPAUSE() {
        return (int) 162L;
    }

    static final int DIK_MEDIASTOP() {
        return (int) 164L;
    }

    static final int DIK_VOLUMEDOWN() {
        return (int) 174L;
    }

    static final int DIK_VOLUMEUP() {
        return (int) 176L;
    }

    static final int DIK_WEBHOME() {
        return (int) 178L;
    }

    static final int DIK_NUMPADCOMMA() {
        return (int) 179L;
    }

    static final int DIK_DIVIDE() {
        return (int) 181L;
    }

    static final int DIK_SYSRQ() {
        return (int) 183L;
    }

    static final int DIK_RMENU() {
        return (int) 184L;
    }

    static final int DIK_PAUSE() {
        return (int) 197L;
    }

    static final int DIK_HOME() {
        return (int) 199L;
    }

    static final int DIK_UP() {
        return (int) 200L;
    }

    static final int DIK_PRIOR() {
        return (int) 201L;
    }

    static final int DIK_LEFT() {
        return (int) 203L;
    }

    static final int DIK_RIGHT() {
        return (int) 205L;
    }

    static final int DIK_END() {
        return (int) 207L;
    }

    static final int DIK_DOWN() {
        return (int) 208L;
    }

    static final int DIK_NEXT() {
        return (int) 209L;
    }

    static final int DIK_INSERT() {
        return (int) 210L;
    }

    static final int DIK_DELETE() {
        return (int) 211L;
    }

    static final int DIK_LWIN() {
        return (int) 219L;
    }

    static final int DIK_RWIN() {
        return (int) 220L;
    }

    static final int DIK_APPS() {
        return (int) 221L;
    }

    static final int DIK_POWER() {
        return (int) 222L;
    }

    static final int DIK_SLEEP() {
        return (int) 223L;
    }

    static final int DIK_WAKE() {
        return (int) 227L;
    }

    static final int DIK_WEBSEARCH() {
        return (int) 229L;
    }

    static final int DIK_WEBFAVORITES() {
        return (int) 230L;
    }

    static final int DIK_WEBREFRESH() {
        return (int) 231L;
    }

    static final int DIK_WEBSTOP() {
        return (int) 232L;
    }

    static final int DIK_WEBFORWARD() {
        return (int) 233L;
    }

    static final int DIK_WEBBACK() {
        return (int) 234L;
    }

    static final int DIK_MYCOMPUTER() {
        return (int) 235L;
    }

    static final int DIK_MAIL() {
        return (int) 236L;
    }

    static final int DIK_MEDIASELECT() {
        return (int) 237L;
    }

    static final int DIENUM_STOP() {
        return (int) 0L;
    }

    static final int DIENUM_CONTINUE() {
        return (int) 1L;
    }

    static final int DIEDFL_ALLDEVICES() {
        return (int) 0L;
    }

    static final int DIEDFL_ATTACHEDONLY() {
        return (int) 1L;
    }

    static final int DIEDFL_FORCEFEEDBACK() {
        return (int) 256L;
    }

    static final int DIEDFL_INCLUDEALIASES() {
        return (int) 65536L;
    }

    static final int DIEDFL_INCLUDEPHANTOMS() {
        return (int) 131072L;
    }

    static final int DIEDFL_INCLUDEHIDDEN() {
        return (int) 262144L;
    }

    static final int DIEDBS_MAPPEDPRI1() {
        return (int) 1L;
    }

    static final int DIEDBS_MAPPEDPRI2() {
        return (int) 2L;
    }

    static final int DIEDBS_RECENTDEVICE() {
        return (int) 16L;
    }

    static final int DIEDBS_NEWDEVICE() {
        return (int) 32L;
    }

    static final int DIEDBSFL_ATTACHEDONLY() {
        return (int) 0L;
    }

    static final int DIEDBSFL_THISUSER() {
        return (int) 16L;
    }

    static final int DIEDBSFL_AVAILABLEDEVICES() {
        return (int) 4096L;
    }

    static final int DIEDBSFL_MULTIMICEKEYBOARDS() {
        return (int) 8192L;
    }

    static final int DIEDBSFL_NONGAMINGDEVICES() {
        return (int) 16384L;
    }

    static final int DIEDBSFL_VALID() {
        return (int) 28944L;
    }

    static final int DIVIRTUAL_DRIVING_RACE() {
        return (int) 16777216L;
    }

    static final int DIAXIS_DRIVINGR_STEER() {
        return (int) 16812545L;
    }

    static final int DIAXIS_DRIVINGR_ACCELERATE() {
        return (int) 17011202L;
    }

    static final int DIAXIS_DRIVINGR_BRAKE() {
        return (int) 17043971L;
    }

    static final int DIBUTTON_DRIVINGR_SHIFTUP() {
        return (int) 16780289L;
    }

    static final int DIBUTTON_DRIVINGR_SHIFTDOWN() {
        return (int) 16780290L;
    }

    static final int DIBUTTON_DRIVINGR_VIEW() {
        return (int) 16784387L;
    }

    static final int DIBUTTON_DRIVINGR_MENU() {
        return (int) 16778493L;
    }

    static final int DIAXIS_DRIVINGR_ACCEL_AND_BRAKE() {
        return (int) 16861700L;
    }

    static final int DIHATSWITCH_DRIVINGR_GLANCE() {
        return (int) 16795137L;
    }

    static final int DIBUTTON_DRIVINGR_BRAKE() {
        return (int) 16796676L;
    }

    static final int DIBUTTON_DRIVINGR_DASHBOARD() {
        return (int) 16794629L;
    }

    static final int DIBUTTON_DRIVINGR_AIDS() {
        return (int) 16794630L;
    }

    static final int DIBUTTON_DRIVINGR_MAP() {
        return (int) 16794631L;
    }

    static final int DIBUTTON_DRIVINGR_BOOST() {
        return (int) 16794632L;
    }

    static final int DIBUTTON_DRIVINGR_PIT() {
        return (int) 16794633L;
    }

    static final int DIBUTTON_DRIVINGR_ACCELERATE_LINK() {
        return (int) 17028320L;
    }

    static final int DIBUTTON_DRIVINGR_STEER_LEFT_LINK() {
        return (int) 16829668L;
    }

    static final int DIBUTTON_DRIVINGR_STEER_RIGHT_LINK() {
        return (int) 16829676L;
    }

    static final int DIBUTTON_DRIVINGR_GLANCE_LEFT_LINK() {
        return (int) 17286372L;
    }

    static final int DIBUTTON_DRIVINGR_GLANCE_RIGHT_LINK() {
        return (int) 17286380L;
    }

    static final int DIBUTTON_DRIVINGR_DEVICE() {
        return (int) 16794878L;
    }

    static final int DIBUTTON_DRIVINGR_PAUSE() {
        return (int) 16794876L;
    }

    static final int DIVIRTUAL_DRIVING_COMBAT() {
        return (int) 33554432L;
    }

    static final int DIAXIS_DRIVINGC_STEER() {
        return (int) 33589761L;
    }

    static final int DIAXIS_DRIVINGC_ACCELERATE() {
        return (int) 33788418L;
    }

    static final int DIAXIS_DRIVINGC_BRAKE() {
        return (int) 33821187L;
    }

    static final int DIBUTTON_DRIVINGC_FIRE() {
        return (int) 33557505L;
    }

    static final int DIBUTTON_DRIVINGC_WEAPONS() {
        return (int) 33557506L;
    }

    static final int DIBUTTON_DRIVINGC_TARGET() {
        return (int) 33557507L;
    }

    static final int DIBUTTON_DRIVINGC_MENU() {
        return (int) 33555709L;
    }

    static final int DIAXIS_DRIVINGC_ACCEL_AND_BRAKE() {
        return (int) 33638916L;
    }

    static final int DIHATSWITCH_DRIVINGC_GLANCE() {
        return (int) 33572353L;
    }

    static final int DIBUTTON_DRIVINGC_SHIFTUP() {
        return (int) 33573892L;
    }

    static final int DIBUTTON_DRIVINGC_SHIFTDOWN() {
        return (int) 33573893L;
    }

    static final int DIBUTTON_DRIVINGC_DASHBOARD() {
        return (int) 33571846L;
    }

    static final int DIBUTTON_DRIVINGC_AIDS() {
        return (int) 33571847L;
    }

    static final int DIBUTTON_DRIVINGC_BRAKE() {
        return (int) 33573896L;
    }

    static final int DIBUTTON_DRIVINGC_FIRESECONDARY() {
        return (int) 33573897L;
    }

    static final int DIBUTTON_DRIVINGC_ACCELERATE_LINK() {
        return (int) 33805536L;
    }

    static final int DIBUTTON_DRIVINGC_STEER_LEFT_LINK() {
        return (int) 33606884L;
    }

    static final int DIBUTTON_DRIVINGC_STEER_RIGHT_LINK() {
        return (int) 33606892L;
    }

    static final int DIBUTTON_DRIVINGC_GLANCE_LEFT_LINK() {
        return (int) 34063588L;
    }

    static final int DIBUTTON_DRIVINGC_GLANCE_RIGHT_LINK() {
        return (int) 34063596L;
    }

    static final int DIBUTTON_DRIVINGC_DEVICE() {
        return (int) 33572094L;
    }

    static final int DIBUTTON_DRIVINGC_PAUSE() {
        return (int) 33572092L;
    }

    static final int DIVIRTUAL_DRIVING_TANK() {
        return (int) 50331648L;
    }

    static final int DIAXIS_DRIVINGT_STEER() {
        return (int) 50366977L;
    }

    static final int DIAXIS_DRIVINGT_BARREL() {
        return (int) 50397698L;
    }

    static final int DIAXIS_DRIVINGT_ACCELERATE() {
        return (int) 50565635L;
    }

    static final int DIAXIS_DRIVINGT_ROTATE() {
        return (int) 50463236L;
    }

    static final int DIBUTTON_DRIVINGT_FIRE() {
        return (int) 50334721L;
    }

    static final int DIBUTTON_DRIVINGT_WEAPONS() {
        return (int) 50334722L;
    }

    static final int DIBUTTON_DRIVINGT_TARGET() {
        return (int) 50334723L;
    }

    static final int DIBUTTON_DRIVINGT_MENU() {
        return (int) 50332925L;
    }

    static final int DIHATSWITCH_DRIVINGT_GLANCE() {
        return (int) 50349569L;
    }

    static final int DIAXIS_DRIVINGT_BRAKE() {
        return (int) 50614789L;
    }

    static final int DIAXIS_DRIVINGT_ACCEL_AND_BRAKE() {
        return (int) 50416134L;
    }

    static final int DIBUTTON_DRIVINGT_VIEW() {
        return (int) 50355204L;
    }

    static final int DIBUTTON_DRIVINGT_DASHBOARD() {
        return (int) 50355205L;
    }

    static final int DIBUTTON_DRIVINGT_BRAKE() {
        return (int) 50351110L;
    }

    static final int DIBUTTON_DRIVINGT_FIRESECONDARY() {
        return (int) 50351111L;
    }

    static final int DIBUTTON_DRIVINGT_ACCELERATE_LINK() {
        return (int) 50582752L;
    }

    static final int DIBUTTON_DRIVINGT_STEER_LEFT_LINK() {
        return (int) 50384100L;
    }

    static final int DIBUTTON_DRIVINGT_STEER_RIGHT_LINK() {
        return (int) 50384108L;
    }

    static final int DIBUTTON_DRIVINGT_BARREL_UP_LINK() {
        return (int) 50414816L;
    }

    static final int DIBUTTON_DRIVINGT_BARREL_DOWN_LINK() {
        return (int) 50414824L;
    }

    static final int DIBUTTON_DRIVINGT_ROTATE_LEFT_LINK() {
        return (int) 50480356L;
    }

    static final int DIBUTTON_DRIVINGT_ROTATE_RIGHT_LINK() {
        return (int) 50480364L;
    }

    static final int DIBUTTON_DRIVINGT_GLANCE_LEFT_LINK() {
        return (int) 50840804L;
    }

    static final int DIBUTTON_DRIVINGT_GLANCE_RIGHT_LINK() {
        return (int) 50840812L;
    }

    static final int DIBUTTON_DRIVINGT_DEVICE() {
        return (int) 50349310L;
    }

    static final int DIBUTTON_DRIVINGT_PAUSE() {
        return (int) 50349308L;
    }

    static final int DIVIRTUAL_FLYING_CIVILIAN() {
        return (int) 67108864L;
    }

    static final int DIAXIS_FLYINGC_BANK() {
        return (int) 67144193L;
    }

    static final int DIAXIS_FLYINGC_PITCH() {
        return (int) 67176962L;
    }

    static final int DIAXIS_FLYINGC_THROTTLE() {
        return (int) 67342851L;
    }

    static final int DIBUTTON_FLYINGC_VIEW() {
        return (int) 67118081L;
    }

    static final int DIBUTTON_FLYINGC_DISPLAY() {
        return (int) 67118082L;
    }

    static final int DIBUTTON_FLYINGC_GEAR() {
        return (int) 67120131L;
    }

    static final int DIBUTTON_FLYINGC_MENU() {
        return (int) 67110141L;
    }

    static final int DIHATSWITCH_FLYINGC_GLANCE() {
        return (int) 67126785L;
    }

    static final int DIAXIS_FLYINGC_BRAKE() {
        return (int) 67398148L;
    }

    static final int DIAXIS_FLYINGC_RUDDER() {
        return (int) 67260933L;
    }

    static final int DIAXIS_FLYINGC_FLAPS() {
        return (int) 67459590L;
    }

    static final int DIBUTTON_FLYINGC_FLAPSUP() {
        return (int) 67134468L;
    }

    static final int DIBUTTON_FLYINGC_FLAPSDOWN() {
        return (int) 67134469L;
    }

    static final int DIBUTTON_FLYINGC_BRAKE_LINK() {
        return (int) 67398880L;
    }

    static final int DIBUTTON_FLYINGC_FASTER_LINK() {
        return (int) 67359968L;
    }

    static final int DIBUTTON_FLYINGC_SLOWER_LINK() {
        return (int) 67359976L;
    }

    static final int DIBUTTON_FLYINGC_GLANCE_LEFT_LINK() {
        return (int) 67618020L;
    }

    static final int DIBUTTON_FLYINGC_GLANCE_RIGHT_LINK() {
        return (int) 67618028L;
    }

    static final int DIBUTTON_FLYINGC_GLANCE_UP_LINK() {
        return (int) 67618016L;
    }

    static final int DIBUTTON_FLYINGC_GLANCE_DOWN_LINK() {
        return (int) 67618024L;
    }

    static final int DIBUTTON_FLYINGC_DEVICE() {
        return (int) 67126526L;
    }

    static final int DIBUTTON_FLYINGC_PAUSE() {
        return (int) 67126524L;
    }

    static final int DIVIRTUAL_FLYING_MILITARY() {
        return (int) 83886080L;
    }

    static final int DIAXIS_FLYINGM_BANK() {
        return (int) 83921409L;
    }

    static final int DIAXIS_FLYINGM_PITCH() {
        return (int) 83954178L;
    }

    static final int DIAXIS_FLYINGM_THROTTLE() {
        return (int) 84120067L;
    }

    static final int DIBUTTON_FLYINGM_FIRE() {
        return (int) 83889153L;
    }

    static final int DIBUTTON_FLYINGM_WEAPONS() {
        return (int) 83889154L;
    }

    static final int DIBUTTON_FLYINGM_TARGET() {
        return (int) 83889155L;
    }

    static final int DIBUTTON_FLYINGM_MENU() {
        return (int) 83887357L;
    }

    static final int DIHATSWITCH_FLYINGM_GLANCE() {
        return (int) 83904001L;
    }

    static final int DIBUTTON_FLYINGM_COUNTER() {
        return (int) 83909636L;
    }

    static final int DIAXIS_FLYINGM_RUDDER() {
        return (int) 84036100L;
    }

    static final int DIAXIS_FLYINGM_BRAKE() {
        return (int) 84173317L;
    }

    static final int DIBUTTON_FLYINGM_VIEW() {
        return (int) 83911685L;
    }

    static final int DIBUTTON_FLYINGM_DISPLAY() {
        return (int) 83911686L;
    }

    static final int DIAXIS_FLYINGM_FLAPS() {
        return (int) 84234758L;
    }

    static final int DIBUTTON_FLYINGM_FLAPSUP() {
        return (int) 83907591L;
    }

    static final int DIBUTTON_FLYINGM_FLAPSDOWN() {
        return (int) 83907592L;
    }

    static final int DIBUTTON_FLYINGM_FIRESECONDARY() {
        return (int) 83905545L;
    }

    static final int DIBUTTON_FLYINGM_GEAR() {
        return (int) 83911690L;
    }

    static final int DIBUTTON_FLYINGM_BRAKE_LINK() {
        return (int) 84174048L;
    }

    static final int DIBUTTON_FLYINGM_FASTER_LINK() {
        return (int) 84137184L;
    }

    static final int DIBUTTON_FLYINGM_SLOWER_LINK() {
        return (int) 84137192L;
    }

    static final int DIBUTTON_FLYINGM_GLANCE_LEFT_LINK() {
        return (int) 84395236L;
    }

    static final int DIBUTTON_FLYINGM_GLANCE_RIGHT_LINK() {
        return (int) 84395244L;
    }

    static final int DIBUTTON_FLYINGM_GLANCE_UP_LINK() {
        return (int) 84395232L;
    }

    static final int DIBUTTON_FLYINGM_GLANCE_DOWN_LINK() {
        return (int) 84395240L;
    }

    static final int DIBUTTON_FLYINGM_DEVICE() {
        return (int) 83903742L;
    }

    static final int DIBUTTON_FLYINGM_PAUSE() {
        return (int) 83903740L;
    }

    static final int DIVIRTUAL_FLYING_HELICOPTER() {
        return (int) 100663296L;
    }

    static final int DIAXIS_FLYINGH_BANK() {
        return (int) 100698625L;
    }

    static final int DIAXIS_FLYINGH_PITCH() {
        return (int) 100731394L;
    }

    static final int DIAXIS_FLYINGH_COLLECTIVE() {
        return (int) 100764163L;
    }

    static final int DIBUTTON_FLYINGH_FIRE() {
        return (int) 100668417L;
    }

    static final int DIBUTTON_FLYINGH_WEAPONS() {
        return (int) 100668418L;
    }

    static final int DIBUTTON_FLYINGH_TARGET() {
        return (int) 100668419L;
    }

    static final int DIBUTTON_FLYINGH_MENU() {
        return (int) 100664573L;
    }

    static final int DIHATSWITCH_FLYINGH_GLANCE() {
        return (int) 100681217L;
    }

    static final int DIAXIS_FLYINGH_TORQUE() {
        return (int) 100817412L;
    }

    static final int DIAXIS_FLYINGH_THROTTLE() {
        return (int) 100915717L;
    }

    static final int DIBUTTON_FLYINGH_COUNTER() {
        return (int) 100684804L;
    }

    static final int DIBUTTON_FLYINGH_VIEW() {
        return (int) 100688901L;
    }

    static final int DIBUTTON_FLYINGH_GEAR() {
        return (int) 100688902L;
    }

    static final int DIBUTTON_FLYINGH_FIRESECONDARY() {
        return (int) 100682759L;
    }

    static final int DIBUTTON_FLYINGH_FASTER_LINK() {
        return (int) 100916448L;
    }

    static final int DIBUTTON_FLYINGH_SLOWER_LINK() {
        return (int) 100916456L;
    }

    static final int DIBUTTON_FLYINGH_GLANCE_LEFT_LINK() {
        return (int) 101172452L;
    }

    static final int DIBUTTON_FLYINGH_GLANCE_RIGHT_LINK() {
        return (int) 101172460L;
    }

    static final int DIBUTTON_FLYINGH_GLANCE_UP_LINK() {
        return (int) 101172448L;
    }

    static final int DIBUTTON_FLYINGH_GLANCE_DOWN_LINK() {
        return (int) 101172456L;
    }

    static final int DIBUTTON_FLYINGH_DEVICE() {
        return (int) 100680958L;
    }

    static final int DIBUTTON_FLYINGH_PAUSE() {
        return (int) 100680956L;
    }

    static final int DIVIRTUAL_SPACESIM() {
        return (int) 117440512L;
    }

    static final int DIAXIS_SPACESIM_LATERAL() {
        return (int) 117473793L;
    }

    static final int DIAXIS_SPACESIM_MOVE() {
        return (int) 117506562L;
    }

    static final int DIAXIS_SPACESIM_THROTTLE() {
        return (int) 117670403L;
    }

    static final int DIBUTTON_SPACESIM_FIRE() {
        return (int) 117441537L;
    }

    static final int DIBUTTON_SPACESIM_WEAPONS() {
        return (int) 117441538L;
    }

    static final int DIBUTTON_SPACESIM_TARGET() {
        return (int) 117441539L;
    }

    static final int DIBUTTON_SPACESIM_MENU() {
        return (int) 117441789L;
    }

    static final int DIHATSWITCH_SPACESIM_GLANCE() {
        return (int) 117458433L;
    }

    static final int DIAXIS_SPACESIM_CLIMB() {
        return (int) 117555716L;
    }

    static final int DIAXIS_SPACESIM_ROTATE() {
        return (int) 117588485L;
    }

    static final int DIBUTTON_SPACESIM_VIEW() {
        return (int) 117457924L;
    }

    static final int DIBUTTON_SPACESIM_DISPLAY() {
        return (int) 117457925L;
    }

    static final int DIBUTTON_SPACESIM_RAISE() {
        return (int) 117457926L;
    }

    static final int DIBUTTON_SPACESIM_LOWER() {
        return (int) 117457927L;
    }

    static final int DIBUTTON_SPACESIM_GEAR() {
        return (int) 117457928L;
    }

    static final int DIBUTTON_SPACESIM_FIRESECONDARY() {
        return (int) 117457929L;
    }

    static final int DIBUTTON_SPACESIM_LEFT_LINK() {
        return (int) 117490916L;
    }

    static final int DIBUTTON_SPACESIM_RIGHT_LINK() {
        return (int) 117490924L;
    }

    static final int DIBUTTON_SPACESIM_FORWARD_LINK() {
        return (int) 117523680L;
    }

    static final int DIBUTTON_SPACESIM_BACKWARD_LINK() {
        return (int) 117523688L;
    }

    static final int DIBUTTON_SPACESIM_FASTER_LINK() {
        return (int) 117687520L;
    }

    static final int DIBUTTON_SPACESIM_SLOWER_LINK() {
        return (int) 117687528L;
    }

    static final int DIBUTTON_SPACESIM_TURN_LEFT_LINK() {
        return (int) 117589220L;
    }

    static final int DIBUTTON_SPACESIM_TURN_RIGHT_LINK() {
        return (int) 117589228L;
    }

    static final int DIBUTTON_SPACESIM_GLANCE_LEFT_LINK() {
        return (int) 117949668L;
    }

    static final int DIBUTTON_SPACESIM_GLANCE_RIGHT_LINK() {
        return (int) 117949676L;
    }

    static final int DIBUTTON_SPACESIM_GLANCE_UP_LINK() {
        return (int) 117949664L;
    }

    static final int DIBUTTON_SPACESIM_GLANCE_DOWN_LINK() {
        return (int) 117949672L;
    }

    static final int DIBUTTON_SPACESIM_DEVICE() {
        return (int) 117458174L;
    }

    static final int DIBUTTON_SPACESIM_PAUSE() {
        return (int) 117458172L;
    }

    static final int DIVIRTUAL_FIGHTING_HAND2HAND() {
        return (int) 134217728L;
    }

    static final int DIAXIS_FIGHTINGH_LATERAL() {
        return (int) 134251009L;
    }

    static final int DIAXIS_FIGHTINGH_MOVE() {
        return (int) 134283778L;
    }

    static final int DIBUTTON_FIGHTINGH_PUNCH() {
        return (int) 134218753L;
    }

    static final int DIBUTTON_FIGHTINGH_KICK() {
        return (int) 134218754L;
    }

    static final int DIBUTTON_FIGHTINGH_BLOCK() {
        return (int) 134218755L;
    }

    static final int DIBUTTON_FIGHTINGH_CROUCH() {
        return (int) 134218756L;
    }

    static final int DIBUTTON_FIGHTINGH_JUMP() {
        return (int) 134218757L;
    }

    static final int DIBUTTON_FIGHTINGH_SPECIAL1() {
        return (int) 134218758L;
    }

    static final int DIBUTTON_FIGHTINGH_SPECIAL2() {
        return (int) 134218759L;
    }

    static final int DIBUTTON_FIGHTINGH_MENU() {
        return (int) 134219005L;
    }

    static final int DIBUTTON_FIGHTINGH_SELECT() {
        return (int) 134235144L;
    }

    static final int DIHATSWITCH_FIGHTINGH_SLIDE() {
        return (int) 134235649L;
    }

    static final int DIBUTTON_FIGHTINGH_DISPLAY() {
        return (int) 134235145L;
    }

    static final int DIAXIS_FIGHTINGH_ROTATE() {
        return (int) 134365699L;
    }

    static final int DIBUTTON_FIGHTINGH_DODGE() {
        return (int) 134235146L;
    }

    static final int DIBUTTON_FIGHTINGH_LEFT_LINK() {
        return (int) 134268132L;
    }

    static final int DIBUTTON_FIGHTINGH_RIGHT_LINK() {
        return (int) 134268140L;
    }

    static final int DIBUTTON_FIGHTINGH_FORWARD_LINK() {
        return (int) 134300896L;
    }

    static final int DIBUTTON_FIGHTINGH_BACKWARD_LINK() {
        return (int) 134300904L;
    }

    static final int DIBUTTON_FIGHTINGH_DEVICE() {
        return (int) 134235390L;
    }

    static final int DIBUTTON_FIGHTINGH_PAUSE() {
        return (int) 134235388L;
    }

    static final int DIVIRTUAL_FIGHTING_FPS() {
        return (int) 150994944L;
    }

    static final int DIAXIS_FPS_ROTATE() {
        return (int) 151028225L;
    }

    static final int DIAXIS_FPS_MOVE() {
        return (int) 151060994L;
    }

    static final int DIBUTTON_FPS_FIRE() {
        return (int) 150995969L;
    }

    static final int DIBUTTON_FPS_WEAPONS() {
        return (int) 150995970L;
    }

    static final int DIBUTTON_FPS_APPLY() {
        return (int) 150995971L;
    }

    static final int DIBUTTON_FPS_SELECT() {
        return (int) 150995972L;
    }

    static final int DIBUTTON_FPS_CROUCH() {
        return (int) 150995973L;
    }

    static final int DIBUTTON_FPS_JUMP() {
        return (int) 150995974L;
    }

    static final int DIAXIS_FPS_LOOKUPDOWN() {
        return (int) 151093763L;
    }

    static final int DIBUTTON_FPS_STRAFE() {
        return (int) 150995975L;
    }

    static final int DIBUTTON_FPS_MENU() {
        return (int) 150996221L;
    }

    static final int DIHATSWITCH_FPS_GLANCE() {
        return (int) 151012865L;
    }

    static final int DIBUTTON_FPS_DISPLAY() {
        return (int) 151012360L;
    }

    static final int DIAXIS_FPS_SIDESTEP() {
        return (int) 151142916L;
    }

    static final int DIBUTTON_FPS_DODGE() {
        return (int) 151012361L;
    }

    static final int DIBUTTON_FPS_GLANCEL() {
        return (int) 151012362L;
    }

    static final int DIBUTTON_FPS_GLANCER() {
        return (int) 151012363L;
    }

    static final int DIBUTTON_FPS_FIRESECONDARY() {
        return (int) 151012364L;
    }

    static final int DIBUTTON_FPS_ROTATE_LEFT_LINK() {
        return (int) 151045348L;
    }

    static final int DIBUTTON_FPS_ROTATE_RIGHT_LINK() {
        return (int) 151045356L;
    }

    static final int DIBUTTON_FPS_FORWARD_LINK() {
        return (int) 151078112L;
    }

    static final int DIBUTTON_FPS_BACKWARD_LINK() {
        return (int) 151078120L;
    }

    static final int DIBUTTON_FPS_GLANCE_UP_LINK() {
        return (int) 151110880L;
    }

    static final int DIBUTTON_FPS_GLANCE_DOWN_LINK() {
        return (int) 151110888L;
    }

    static final int DIBUTTON_FPS_STEP_LEFT_LINK() {
        return (int) 151143652L;
    }

    static final int DIBUTTON_FPS_STEP_RIGHT_LINK() {
        return (int) 151143660L;
    }

    static final int DIBUTTON_FPS_DEVICE() {
        return (int) 151012606L;
    }

    static final int DIBUTTON_FPS_PAUSE() {
        return (int) 151012604L;
    }

    static final int DIVIRTUAL_FIGHTING_THIRDPERSON() {
        return (int) 167772160L;
    }

    static final int DIAXIS_TPS_TURN() {
        return (int) 167903745L;
    }

    static final int DIAXIS_TPS_MOVE() {
        return (int) 167838210L;
    }

    static final int DIBUTTON_TPS_RUN() {
        return (int) 167773185L;
    }

    static final int DIBUTTON_TPS_ACTION() {
        return (int) 167773186L;
    }

    static final int DIBUTTON_TPS_SELECT() {
        return (int) 167773187L;
    }

    static final int DIBUTTON_TPS_USE() {
        return (int) 167773188L;
    }

    static final int DIBUTTON_TPS_JUMP() {
        return (int) 167773189L;
    }

    static final int DIBUTTON_TPS_MENU() {
        return (int) 167773437L;
    }

    static final int DIHATSWITCH_TPS_GLANCE() {
        return (int) 167790081L;
    }

    static final int DIBUTTON_TPS_VIEW() {
        return (int) 167789574L;
    }

    static final int DIBUTTON_TPS_STEPLEFT() {
        return (int) 167789575L;
    }

    static final int DIBUTTON_TPS_STEPRIGHT() {
        return (int) 167789576L;
    }

    static final int DIAXIS_TPS_STEP() {
        return (int) 167821827L;
    }

    static final int DIBUTTON_TPS_DODGE() {
        return (int) 167789577L;
    }

    static final int DIBUTTON_TPS_INVENTORY() {
        return (int) 167789578L;
    }

    static final int DIBUTTON_TPS_TURN_LEFT_LINK() {
        return (int) 167920868L;
    }

    static final int DIBUTTON_TPS_TURN_RIGHT_LINK() {
        return (int) 167920876L;
    }

    static final int DIBUTTON_TPS_FORWARD_LINK() {
        return (int) 167855328L;
    }

    static final int DIBUTTON_TPS_BACKWARD_LINK() {
        return (int) 167855336L;
    }

    static final int DIBUTTON_TPS_GLANCE_UP_LINK() {
        return (int) 168281312L;
    }

    static final int DIBUTTON_TPS_GLANCE_DOWN_LINK() {
        return (int) 168281320L;
    }

    static final int DIBUTTON_TPS_GLANCE_LEFT_LINK() {
        return (int) 168281316L;
    }

    static final int DIBUTTON_TPS_GLANCE_RIGHT_LINK() {
        return (int) 168281324L;
    }

    static final int DIBUTTON_TPS_DEVICE() {
        return (int) 167789822L;
    }

    static final int DIBUTTON_TPS_PAUSE() {
        return (int) 167789820L;
    }

    static final int DIVIRTUAL_STRATEGY_ROLEPLAYING() {
        return (int) 184549376L;
    }

    static final int DIAXIS_STRATEGYR_LATERAL() {
        return (int) 184582657L;
    }

    static final int DIAXIS_STRATEGYR_MOVE() {
        return (int) 184615426L;
    }

    static final int DIBUTTON_STRATEGYR_GET() {
        return (int) 184550401L;
    }

    static final int DIBUTTON_STRATEGYR_APPLY() {
        return (int) 184550402L;
    }

    static final int DIBUTTON_STRATEGYR_SELECT() {
        return (int) 184550403L;
    }

    static final int DIBUTTON_STRATEGYR_ATTACK() {
        return (int) 184550404L;
    }

    static final int DIBUTTON_STRATEGYR_CAST() {
        return (int) 184550405L;
    }

    static final int DIBUTTON_STRATEGYR_CROUCH() {
        return (int) 184550406L;
    }

    static final int DIBUTTON_STRATEGYR_JUMP() {
        return (int) 184550407L;
    }

    static final int DIBUTTON_STRATEGYR_MENU() {
        return (int) 184550653L;
    }

    static final int DIHATSWITCH_STRATEGYR_GLANCE() {
        return (int) 184567297L;
    }

    static final int DIBUTTON_STRATEGYR_MAP() {
        return (int) 184566792L;
    }

    static final int DIBUTTON_STRATEGYR_DISPLAY() {
        return (int) 184566793L;
    }

    static final int DIAXIS_STRATEGYR_ROTATE() {
        return (int) 184697347L;
    }

    static final int DIBUTTON_STRATEGYR_LEFT_LINK() {
        return (int) 184599780L;
    }

    static final int DIBUTTON_STRATEGYR_RIGHT_LINK() {
        return (int) 184599788L;
    }

    static final int DIBUTTON_STRATEGYR_FORWARD_LINK() {
        return (int) 184632544L;
    }

    static final int DIBUTTON_STRATEGYR_BACK_LINK() {
        return (int) 184632552L;
    }

    static final int DIBUTTON_STRATEGYR_ROTATE_LEFT_LINK() {
        return (int) 184698084L;
    }

    static final int DIBUTTON_STRATEGYR_ROTATE_RIGHT_LINK() {
        return (int) 184698092L;
    }

    static final int DIBUTTON_STRATEGYR_DEVICE() {
        return (int) 184567038L;
    }

    static final int DIBUTTON_STRATEGYR_PAUSE() {
        return (int) 184567036L;
    }

    static final int DIVIRTUAL_STRATEGY_TURN() {
        return (int) 201326592L;
    }

    static final int DIAXIS_STRATEGYT_LATERAL() {
        return (int) 201359873L;
    }

    static final int DIAXIS_STRATEGYT_MOVE() {
        return (int) 201392642L;
    }

    static final int DIBUTTON_STRATEGYT_SELECT() {
        return (int) 201327617L;
    }

    static final int DIBUTTON_STRATEGYT_INSTRUCT() {
        return (int) 201327618L;
    }

    static final int DIBUTTON_STRATEGYT_APPLY() {
        return (int) 201327619L;
    }

    static final int DIBUTTON_STRATEGYT_TEAM() {
        return (int) 201327620L;
    }

    static final int DIBUTTON_STRATEGYT_TURN() {
        return (int) 201327621L;
    }

    static final int DIBUTTON_STRATEGYT_MENU() {
        return (int) 201327869L;
    }

    static final int DIBUTTON_STRATEGYT_ZOOM() {
        return (int) 201344006L;
    }

    static final int DIBUTTON_STRATEGYT_MAP() {
        return (int) 201344007L;
    }

    static final int DIBUTTON_STRATEGYT_DISPLAY() {
        return (int) 201344008L;
    }

    static final int DIBUTTON_STRATEGYT_LEFT_LINK() {
        return (int) 201376996L;
    }

    static final int DIBUTTON_STRATEGYT_RIGHT_LINK() {
        return (int) 201377004L;
    }

    static final int DIBUTTON_STRATEGYT_FORWARD_LINK() {
        return (int) 201409760L;
    }

    static final int DIBUTTON_STRATEGYT_BACK_LINK() {
        return (int) 201409768L;
    }

    static final int DIBUTTON_STRATEGYT_DEVICE() {
        return (int) 201344254L;
    }

    static final int DIBUTTON_STRATEGYT_PAUSE() {
        return (int) 201344252L;
    }

    static final int DIVIRTUAL_SPORTS_HUNTING() {
        return (int) 218103808L;
    }

    static final int DIAXIS_HUNTING_LATERAL() {
        return (int) 218137089L;
    }

    static final int DIAXIS_HUNTING_MOVE() {
        return (int) 218169858L;
    }

    static final int DIBUTTON_HUNTING_FIRE() {
        return (int) 218104833L;
    }

    static final int DIBUTTON_HUNTING_AIM() {
        return (int) 218104834L;
    }

    static final int DIBUTTON_HUNTING_WEAPON() {
        return (int) 218104835L;
    }

    static final int DIBUTTON_HUNTING_BINOCULAR() {
        return (int) 218104836L;
    }

    static final int DIBUTTON_HUNTING_CALL() {
        return (int) 218104837L;
    }

    static final int DIBUTTON_HUNTING_MAP() {
        return (int) 218104838L;
    }

    static final int DIBUTTON_HUNTING_SPECIAL() {
        return (int) 218104839L;
    }

    static final int DIBUTTON_HUNTING_MENU() {
        return (int) 218105085L;
    }

    static final int DIHATSWITCH_HUNTING_GLANCE() {
        return (int) 218121729L;
    }

    static final int DIBUTTON_HUNTING_DISPLAY() {
        return (int) 218121224L;
    }

    static final int DIAXIS_HUNTING_ROTATE() {
        return (int) 218251779L;
    }

    static final int DIBUTTON_HUNTING_CROUCH() {
        return (int) 218121225L;
    }

    static final int DIBUTTON_HUNTING_JUMP() {
        return (int) 218121226L;
    }

    static final int DIBUTTON_HUNTING_FIRESECONDARY() {
        return (int) 218121227L;
    }

    static final int DIBUTTON_HUNTING_LEFT_LINK() {
        return (int) 218154212L;
    }

    static final int DIBUTTON_HUNTING_RIGHT_LINK() {
        return (int) 218154220L;
    }

    static final int DIBUTTON_HUNTING_FORWARD_LINK() {
        return (int) 218186976L;
    }

    static final int DIBUTTON_HUNTING_BACK_LINK() {
        return (int) 218186984L;
    }

    static final int DIBUTTON_HUNTING_ROTATE_LEFT_LINK() {
        return (int) 218252516L;
    }

    static final int DIBUTTON_HUNTING_ROTATE_RIGHT_LINK() {
        return (int) 218252524L;
    }

    static final int DIBUTTON_HUNTING_DEVICE() {
        return (int) 218121470L;
    }

    static final int DIBUTTON_HUNTING_PAUSE() {
        return (int) 218121468L;
    }

    static final int DIVIRTUAL_SPORTS_FISHING() {
        return (int) 234881024L;
    }

    static final int DIAXIS_FISHING_LATERAL() {
        return (int) 234914305L;
    }

    static final int DIAXIS_FISHING_MOVE() {
        return (int) 234947074L;
    }

    static final int DIBUTTON_FISHING_CAST() {
        return (int) 234882049L;
    }

    static final int DIBUTTON_FISHING_TYPE() {
        return (int) 234882050L;
    }

    static final int DIBUTTON_FISHING_BINOCULAR() {
        return (int) 234882051L;
    }

    static final int DIBUTTON_FISHING_BAIT() {
        return (int) 234882052L;
    }

    static final int DIBUTTON_FISHING_MAP() {
        return (int) 234882053L;
    }

    static final int DIBUTTON_FISHING_MENU() {
        return (int) 234882301L;
    }

    static final int DIHATSWITCH_FISHING_GLANCE() {
        return (int) 234898945L;
    }

    static final int DIBUTTON_FISHING_DISPLAY() {
        return (int) 234898438L;
    }

    static final int DIAXIS_FISHING_ROTATE() {
        return (int) 235028995L;
    }

    static final int DIBUTTON_FISHING_CROUCH() {
        return (int) 234898439L;
    }

    static final int DIBUTTON_FISHING_JUMP() {
        return (int) 234898440L;
    }

    static final int DIBUTTON_FISHING_LEFT_LINK() {
        return (int) 234931428L;
    }

    static final int DIBUTTON_FISHING_RIGHT_LINK() {
        return (int) 234931436L;
    }

    static final int DIBUTTON_FISHING_FORWARD_LINK() {
        return (int) 234964192L;
    }

    static final int DIBUTTON_FISHING_BACK_LINK() {
        return (int) 234964200L;
    }

    static final int DIBUTTON_FISHING_ROTATE_LEFT_LINK() {
        return (int) 235029732L;
    }

    static final int DIBUTTON_FISHING_ROTATE_RIGHT_LINK() {
        return (int) 235029740L;
    }

    static final int DIBUTTON_FISHING_DEVICE() {
        return (int) 234898686L;
    }

    static final int DIBUTTON_FISHING_PAUSE() {
        return (int) 234898684L;
    }

    static final int DIVIRTUAL_SPORTS_BASEBALL_BAT() {
        return (int) 251658240L;
    }

    static final int DIAXIS_BASEBALLB_LATERAL() {
        return (int) 251691521L;
    }

    static final int DIAXIS_BASEBALLB_MOVE() {
        return (int) 251724290L;
    }

    static final int DIBUTTON_BASEBALLB_SELECT() {
        return (int) 251659265L;
    }

    static final int DIBUTTON_BASEBALLB_NORMAL() {
        return (int) 251659266L;
    }

    static final int DIBUTTON_BASEBALLB_POWER() {
        return (int) 251659267L;
    }

    static final int DIBUTTON_BASEBALLB_BUNT() {
        return (int) 251659268L;
    }

    static final int DIBUTTON_BASEBALLB_STEAL() {
        return (int) 251659269L;
    }

    static final int DIBUTTON_BASEBALLB_BURST() {
        return (int) 251659270L;
    }

    static final int DIBUTTON_BASEBALLB_SLIDE() {
        return (int) 251659271L;
    }

    static final int DIBUTTON_BASEBALLB_CONTACT() {
        return (int) 251659272L;
    }

    static final int DIBUTTON_BASEBALLB_MENU() {
        return (int) 251659517L;
    }

    static final int DIBUTTON_BASEBALLB_NOSTEAL() {
        return (int) 251675657L;
    }

    static final int DIBUTTON_BASEBALLB_BOX() {
        return (int) 251675658L;
    }

    static final int DIBUTTON_BASEBALLB_LEFT_LINK() {
        return (int) 251708644L;
    }

    static final int DIBUTTON_BASEBALLB_RIGHT_LINK() {
        return (int) 251708652L;
    }

    static final int DIBUTTON_BASEBALLB_FORWARD_LINK() {
        return (int) 251741408L;
    }

    static final int DIBUTTON_BASEBALLB_BACK_LINK() {
        return (int) 251741416L;
    }

    static final int DIBUTTON_BASEBALLB_DEVICE() {
        return (int) 251675902L;
    }

    static final int DIBUTTON_BASEBALLB_PAUSE() {
        return (int) 251675900L;
    }

    static final int DIVIRTUAL_SPORTS_BASEBALL_PITCH() {
        return (int) 268435456L;
    }

    static final int DIAXIS_BASEBALLP_LATERAL() {
        return (int) 268468737L;
    }

    static final int DIAXIS_BASEBALLP_MOVE() {
        return (int) 268501506L;
    }

    static final int DIBUTTON_BASEBALLP_SELECT() {
        return (int) 268436481L;
    }

    static final int DIBUTTON_BASEBALLP_PITCH() {
        return (int) 268436482L;
    }

    static final int DIBUTTON_BASEBALLP_BASE() {
        return (int) 268436483L;
    }

    static final int DIBUTTON_BASEBALLP_THROW() {
        return (int) 268436484L;
    }

    static final int DIBUTTON_BASEBALLP_FAKE() {
        return (int) 268436485L;
    }

    static final int DIBUTTON_BASEBALLP_MENU() {
        return (int) 268436733L;
    }

    static final int DIBUTTON_BASEBALLP_WALK() {
        return (int) 268452870L;
    }

    static final int DIBUTTON_BASEBALLP_LOOK() {
        return (int) 268452871L;
    }

    static final int DIBUTTON_BASEBALLP_LEFT_LINK() {
        return (int) 268485860L;
    }

    static final int DIBUTTON_BASEBALLP_RIGHT_LINK() {
        return (int) 268485868L;
    }

    static final int DIBUTTON_BASEBALLP_FORWARD_LINK() {
        return (int) 268518624L;
    }

    static final int DIBUTTON_BASEBALLP_BACK_LINK() {
        return (int) 268518632L;
    }

    static final int DIBUTTON_BASEBALLP_DEVICE() {
        return (int) 268453118L;
    }

    static final int DIBUTTON_BASEBALLP_PAUSE() {
        return (int) 268453116L;
    }

    static final int DIVIRTUAL_SPORTS_BASEBALL_FIELD() {
        return (int) 285212672L;
    }

    static final int DIAXIS_BASEBALLF_LATERAL() {
        return (int) 285245953L;
    }

    static final int DIAXIS_BASEBALLF_MOVE() {
        return (int) 285278722L;
    }

    static final int DIBUTTON_BASEBALLF_NEAREST() {
        return (int) 285213697L;
    }

    static final int DIBUTTON_BASEBALLF_THROW1() {
        return (int) 285213698L;
    }

    static final int DIBUTTON_BASEBALLF_THROW2() {
        return (int) 285213699L;
    }

    static final int DIBUTTON_BASEBALLF_BURST() {
        return (int) 285213700L;
    }

    static final int DIBUTTON_BASEBALLF_JUMP() {
        return (int) 285213701L;
    }

    static final int DIBUTTON_BASEBALLF_DIVE() {
        return (int) 285213702L;
    }

    static final int DIBUTTON_BASEBALLF_MENU() {
        return (int) 285213949L;
    }

    static final int DIBUTTON_BASEBALLF_SHIFTIN() {
        return (int) 285230087L;
    }

    static final int DIBUTTON_BASEBALLF_SHIFTOUT() {
        return (int) 285230088L;
    }

    static final int DIBUTTON_BASEBALLF_AIM_LEFT_LINK() {
        return (int) 285263076L;
    }

    static final int DIBUTTON_BASEBALLF_AIM_RIGHT_LINK() {
        return (int) 285263084L;
    }

    static final int DIBUTTON_BASEBALLF_FORWARD_LINK() {
        return (int) 285295840L;
    }

    static final int DIBUTTON_BASEBALLF_BACK_LINK() {
        return (int) 285295848L;
    }

    static final int DIBUTTON_BASEBALLF_DEVICE() {
        return (int) 285230334L;
    }

    static final int DIBUTTON_BASEBALLF_PAUSE() {
        return (int) 285230332L;
    }

    static final int DIVIRTUAL_SPORTS_BASKETBALL_OFFENSE() {
        return (int) 301989888L;
    }

    static final int DIAXIS_BBALLO_LATERAL() {
        return (int) 302023169L;
    }

    static final int DIAXIS_BBALLO_MOVE() {
        return (int) 302055938L;
    }

    static final int DIBUTTON_BBALLO_SHOOT() {
        return (int) 301990913L;
    }

    static final int DIBUTTON_BBALLO_DUNK() {
        return (int) 301990914L;
    }

    static final int DIBUTTON_BBALLO_PASS() {
        return (int) 301990915L;
    }

    static final int DIBUTTON_BBALLO_FAKE() {
        return (int) 301990916L;
    }

    static final int DIBUTTON_BBALLO_SPECIAL() {
        return (int) 301990917L;
    }

    static final int DIBUTTON_BBALLO_PLAYER() {
        return (int) 301990918L;
    }

    static final int DIBUTTON_BBALLO_BURST() {
        return (int) 301990919L;
    }

    static final int DIBUTTON_BBALLO_CALL() {
        return (int) 301990920L;
    }

    static final int DIBUTTON_BBALLO_MENU() {
        return (int) 301991165L;
    }

    static final int DIHATSWITCH_BBALLO_GLANCE() {
        return (int) 302007809L;
    }

    static final int DIBUTTON_BBALLO_SCREEN() {
        return (int) 302007305L;
    }

    static final int DIBUTTON_BBALLO_PLAY() {
        return (int) 302007306L;
    }

    static final int DIBUTTON_BBALLO_JAB() {
        return (int) 302007307L;
    }

    static final int DIBUTTON_BBALLO_POST() {
        return (int) 302007308L;
    }

    static final int DIBUTTON_BBALLO_TIMEOUT() {
        return (int) 302007309L;
    }

    static final int DIBUTTON_BBALLO_SUBSTITUTE() {
        return (int) 302007310L;
    }

    static final int DIBUTTON_BBALLO_LEFT_LINK() {
        return (int) 302040292L;
    }

    static final int DIBUTTON_BBALLO_RIGHT_LINK() {
        return (int) 302040300L;
    }

    static final int DIBUTTON_BBALLO_FORWARD_LINK() {
        return (int) 302073056L;
    }

    static final int DIBUTTON_BBALLO_BACK_LINK() {
        return (int) 302073064L;
    }

    static final int DIBUTTON_BBALLO_DEVICE() {
        return (int) 302007550L;
    }

    static final int DIBUTTON_BBALLO_PAUSE() {
        return (int) 302007548L;
    }

    static final int DIVIRTUAL_SPORTS_BASKETBALL_DEFENSE() {
        return (int) 318767104L;
    }

    static final int DIAXIS_BBALLD_LATERAL() {
        return (int) 318800385L;
    }

    static final int DIAXIS_BBALLD_MOVE() {
        return (int) 318833154L;
    }

    static final int DIBUTTON_BBALLD_JUMP() {
        return (int) 318768129L;
    }

    static final int DIBUTTON_BBALLD_STEAL() {
        return (int) 318768130L;
    }

    static final int DIBUTTON_BBALLD_FAKE() {
        return (int) 318768131L;
    }

    static final int DIBUTTON_BBALLD_SPECIAL() {
        return (int) 318768132L;
    }

    static final int DIBUTTON_BBALLD_PLAYER() {
        return (int) 318768133L;
    }

    static final int DIBUTTON_BBALLD_BURST() {
        return (int) 318768134L;
    }

    static final int DIBUTTON_BBALLD_PLAY() {
        return (int) 318768135L;
    }

    static final int DIBUTTON_BBALLD_MENU() {
        return (int) 318768381L;
    }

    static final int DIHATSWITCH_BBALLD_GLANCE() {
        return (int) 318785025L;
    }

    static final int DIBUTTON_BBALLD_TIMEOUT() {
        return (int) 318784520L;
    }

    static final int DIBUTTON_BBALLD_SUBSTITUTE() {
        return (int) 318784521L;
    }

    static final int DIBUTTON_BBALLD_LEFT_LINK() {
        return (int) 318817508L;
    }

    static final int DIBUTTON_BBALLD_RIGHT_LINK() {
        return (int) 318817516L;
    }

    static final int DIBUTTON_BBALLD_FORWARD_LINK() {
        return (int) 318850272L;
    }

    static final int DIBUTTON_BBALLD_BACK_LINK() {
        return (int) 318850280L;
    }

    static final int DIBUTTON_BBALLD_DEVICE() {
        return (int) 318784766L;
    }

    static final int DIBUTTON_BBALLD_PAUSE() {
        return (int) 318784764L;
    }

    static final int DIVIRTUAL_SPORTS_FOOTBALL_FIELD() {
        return (int) 335544320L;
    }

    static final int DIBUTTON_FOOTBALLP_PLAY() {
        return (int) 335545345L;
    }

    static final int DIBUTTON_FOOTBALLP_SELECT() {
        return (int) 335545346L;
    }

    static final int DIBUTTON_FOOTBALLP_HELP() {
        return (int) 335545347L;
    }

    static final int DIBUTTON_FOOTBALLP_MENU() {
        return (int) 335545597L;
    }

    static final int DIBUTTON_FOOTBALLP_DEVICE() {
        return (int) 335561982L;
    }

    static final int DIBUTTON_FOOTBALLP_PAUSE() {
        return (int) 335561980L;
    }

    static final int DIVIRTUAL_SPORTS_FOOTBALL_QBCK() {
        return (int) 352321536L;
    }

    static final int DIAXIS_FOOTBALLQ_LATERAL() {
        return (int) 352354817L;
    }

    static final int DIAXIS_FOOTBALLQ_MOVE() {
        return (int) 352387586L;
    }

    static final int DIBUTTON_FOOTBALLQ_SELECT() {
        return (int) 352322561L;
    }

    static final int DIBUTTON_FOOTBALLQ_SNAP() {
        return (int) 352322562L;
    }

    static final int DIBUTTON_FOOTBALLQ_JUMP() {
        return (int) 352322563L;
    }

    static final int DIBUTTON_FOOTBALLQ_SLIDE() {
        return (int) 352322564L;
    }

    static final int DIBUTTON_FOOTBALLQ_PASS() {
        return (int) 352322565L;
    }

    static final int DIBUTTON_FOOTBALLQ_FAKE() {
        return (int) 352322566L;
    }

    static final int DIBUTTON_FOOTBALLQ_MENU() {
        return (int) 352322813L;
    }

    static final int DIBUTTON_FOOTBALLQ_FAKESNAP() {
        return (int) 352338951L;
    }

    static final int DIBUTTON_FOOTBALLQ_MOTION() {
        return (int) 352338952L;
    }

    static final int DIBUTTON_FOOTBALLQ_AUDIBLE() {
        return (int) 352338953L;
    }

    static final int DIBUTTON_FOOTBALLQ_LEFT_LINK() {
        return (int) 352371940L;
    }

    static final int DIBUTTON_FOOTBALLQ_RIGHT_LINK() {
        return (int) 352371948L;
    }

    static final int DIBUTTON_FOOTBALLQ_FORWARD_LINK() {
        return (int) 352404704L;
    }

    static final int DIBUTTON_FOOTBALLQ_BACK_LINK() {
        return (int) 352404712L;
    }

    static final int DIBUTTON_FOOTBALLQ_DEVICE() {
        return (int) 352339198L;
    }

    static final int DIBUTTON_FOOTBALLQ_PAUSE() {
        return (int) 352339196L;
    }

    static final int DIVIRTUAL_SPORTS_FOOTBALL_OFFENSE() {
        return (int) 369098752L;
    }

    static final int DIAXIS_FOOTBALLO_LATERAL() {
        return (int) 369132033L;
    }

    static final int DIAXIS_FOOTBALLO_MOVE() {
        return (int) 369164802L;
    }

    static final int DIBUTTON_FOOTBALLO_JUMP() {
        return (int) 369099777L;
    }

    static final int DIBUTTON_FOOTBALLO_LEFTARM() {
        return (int) 369099778L;
    }

    static final int DIBUTTON_FOOTBALLO_RIGHTARM() {
        return (int) 369099779L;
    }

    static final int DIBUTTON_FOOTBALLO_THROW() {
        return (int) 369099780L;
    }

    static final int DIBUTTON_FOOTBALLO_SPIN() {
        return (int) 369099781L;
    }

    static final int DIBUTTON_FOOTBALLO_MENU() {
        return (int) 369100029L;
    }

    static final int DIBUTTON_FOOTBALLO_JUKE() {
        return (int) 369116166L;
    }

    static final int DIBUTTON_FOOTBALLO_SHOULDER() {
        return (int) 369116167L;
    }

    static final int DIBUTTON_FOOTBALLO_TURBO() {
        return (int) 369116168L;
    }

    static final int DIBUTTON_FOOTBALLO_DIVE() {
        return (int) 369116169L;
    }

    static final int DIBUTTON_FOOTBALLO_ZOOM() {
        return (int) 369116170L;
    }

    static final int DIBUTTON_FOOTBALLO_SUBSTITUTE() {
        return (int) 369116171L;
    }

    static final int DIBUTTON_FOOTBALLO_LEFT_LINK() {
        return (int) 369149156L;
    }

    static final int DIBUTTON_FOOTBALLO_RIGHT_LINK() {
        return (int) 369149164L;
    }

    static final int DIBUTTON_FOOTBALLO_FORWARD_LINK() {
        return (int) 369181920L;
    }

    static final int DIBUTTON_FOOTBALLO_BACK_LINK() {
        return (int) 369181928L;
    }

    static final int DIBUTTON_FOOTBALLO_DEVICE() {
        return (int) 369116414L;
    }

    static final int DIBUTTON_FOOTBALLO_PAUSE() {
        return (int) 369116412L;
    }

    static final int DIVIRTUAL_SPORTS_FOOTBALL_DEFENSE() {
        return (int) 385875968L;
    }

    static final int DIAXIS_FOOTBALLD_LATERAL() {
        return (int) 385909249L;
    }

    static final int DIAXIS_FOOTBALLD_MOVE() {
        return (int) 385942018L;
    }

    static final int DIBUTTON_FOOTBALLD_PLAY() {
        return (int) 385876993L;
    }

    static final int DIBUTTON_FOOTBALLD_SELECT() {
        return (int) 385876994L;
    }

    static final int DIBUTTON_FOOTBALLD_JUMP() {
        return (int) 385876995L;
    }

    static final int DIBUTTON_FOOTBALLD_TACKLE() {
        return (int) 385876996L;
    }

    static final int DIBUTTON_FOOTBALLD_FAKE() {
        return (int) 385876997L;
    }

    static final int DIBUTTON_FOOTBALLD_SUPERTACKLE() {
        return (int) 385876998L;
    }

    static final int DIBUTTON_FOOTBALLD_MENU() {
        return (int) 385877245L;
    }

    static final int DIBUTTON_FOOTBALLD_SPIN() {
        return (int) 385893383L;
    }

    static final int DIBUTTON_FOOTBALLD_SWIM() {
        return (int) 385893384L;
    }

    static final int DIBUTTON_FOOTBALLD_BULLRUSH() {
        return (int) 385893385L;
    }

    static final int DIBUTTON_FOOTBALLD_RIP() {
        return (int) 385893386L;
    }

    static final int DIBUTTON_FOOTBALLD_AUDIBLE() {
        return (int) 385893387L;
    }

    static final int DIBUTTON_FOOTBALLD_ZOOM() {
        return (int) 385893388L;
    }

    static final int DIBUTTON_FOOTBALLD_SUBSTITUTE() {
        return (int) 385893389L;
    }

    static final int DIBUTTON_FOOTBALLD_LEFT_LINK() {
        return (int) 385926372L;
    }

    static final int DIBUTTON_FOOTBALLD_RIGHT_LINK() {
        return (int) 385926380L;
    }

    static final int DIBUTTON_FOOTBALLD_FORWARD_LINK() {
        return (int) 385959136L;
    }

    static final int DIBUTTON_FOOTBALLD_BACK_LINK() {
        return (int) 385959144L;
    }

    static final int DIBUTTON_FOOTBALLD_DEVICE() {
        return (int) 385893630L;
    }

    static final int DIBUTTON_FOOTBALLD_PAUSE() {
        return (int) 385893628L;
    }

    static final int DIVIRTUAL_SPORTS_GOLF() {
        return (int) 402653184L;
    }

    static final int DIAXIS_GOLF_LATERAL() {
        return (int) 402686465L;
    }

    static final int DIAXIS_GOLF_MOVE() {
        return (int) 402719234L;
    }

    static final int DIBUTTON_GOLF_SWING() {
        return (int) 402654209L;
    }

    static final int DIBUTTON_GOLF_SELECT() {
        return (int) 402654210L;
    }

    static final int DIBUTTON_GOLF_UP() {
        return (int) 402654211L;
    }

    static final int DIBUTTON_GOLF_DOWN() {
        return (int) 402654212L;
    }

    static final int DIBUTTON_GOLF_TERRAIN() {
        return (int) 402654213L;
    }

    static final int DIBUTTON_GOLF_FLYBY() {
        return (int) 402654214L;
    }

    static final int DIBUTTON_GOLF_MENU() {
        return (int) 402654461L;
    }

    static final int DIHATSWITCH_GOLF_SCROLL() {
        return (int) 402671105L;
    }

    static final int DIBUTTON_GOLF_ZOOM() {
        return (int) 402670599L;
    }

    static final int DIBUTTON_GOLF_TIMEOUT() {
        return (int) 402670600L;
    }

    static final int DIBUTTON_GOLF_SUBSTITUTE() {
        return (int) 402670601L;
    }

    static final int DIBUTTON_GOLF_LEFT_LINK() {
        return (int) 402703588L;
    }

    static final int DIBUTTON_GOLF_RIGHT_LINK() {
        return (int) 402703596L;
    }

    static final int DIBUTTON_GOLF_FORWARD_LINK() {
        return (int) 402736352L;
    }

    static final int DIBUTTON_GOLF_BACK_LINK() {
        return (int) 402736360L;
    }

    static final int DIBUTTON_GOLF_DEVICE() {
        return (int) 402670846L;
    }

    static final int DIBUTTON_GOLF_PAUSE() {
        return (int) 402670844L;
    }

    static final int DIVIRTUAL_SPORTS_HOCKEY_OFFENSE() {
        return (int) 419430400L;
    }

    static final int DIAXIS_HOCKEYO_LATERAL() {
        return (int) 419463681L;
    }

    static final int DIAXIS_HOCKEYO_MOVE() {
        return (int) 419496450L;
    }

    static final int DIBUTTON_HOCKEYO_SHOOT() {
        return (int) 419431425L;
    }

    static final int DIBUTTON_HOCKEYO_PASS() {
        return (int) 419431426L;
    }

    static final int DIBUTTON_HOCKEYO_BURST() {
        return (int) 419431427L;
    }

    static final int DIBUTTON_HOCKEYO_SPECIAL() {
        return (int) 419431428L;
    }

    static final int DIBUTTON_HOCKEYO_FAKE() {
        return (int) 419431429L;
    }

    static final int DIBUTTON_HOCKEYO_MENU() {
        return (int) 419431677L;
    }

    static final int DIHATSWITCH_HOCKEYO_SCROLL() {
        return (int) 419448321L;
    }

    static final int DIBUTTON_HOCKEYO_ZOOM() {
        return (int) 419447814L;
    }

    static final int DIBUTTON_HOCKEYO_STRATEGY() {
        return (int) 419447815L;
    }

    static final int DIBUTTON_HOCKEYO_TIMEOUT() {
        return (int) 419447816L;
    }

    static final int DIBUTTON_HOCKEYO_SUBSTITUTE() {
        return (int) 419447817L;
    }

    static final int DIBUTTON_HOCKEYO_LEFT_LINK() {
        return (int) 419480804L;
    }

    static final int DIBUTTON_HOCKEYO_RIGHT_LINK() {
        return (int) 419480812L;
    }

    static final int DIBUTTON_HOCKEYO_FORWARD_LINK() {
        return (int) 419513568L;
    }

    static final int DIBUTTON_HOCKEYO_BACK_LINK() {
        return (int) 419513576L;
    }

    static final int DIBUTTON_HOCKEYO_DEVICE() {
        return (int) 419448062L;
    }

    static final int DIBUTTON_HOCKEYO_PAUSE() {
        return (int) 419448060L;
    }

    static final int DIVIRTUAL_SPORTS_HOCKEY_DEFENSE() {
        return (int) 436207616L;
    }

    static final int DIAXIS_HOCKEYD_LATERAL() {
        return (int) 436240897L;
    }

    static final int DIAXIS_HOCKEYD_MOVE() {
        return (int) 436273666L;
    }

    static final int DIBUTTON_HOCKEYD_PLAYER() {
        return (int) 436208641L;
    }

    static final int DIBUTTON_HOCKEYD_STEAL() {
        return (int) 436208642L;
    }

    static final int DIBUTTON_HOCKEYD_BURST() {
        return (int) 436208643L;
    }

    static final int DIBUTTON_HOCKEYD_BLOCK() {
        return (int) 436208644L;
    }

    static final int DIBUTTON_HOCKEYD_FAKE() {
        return (int) 436208645L;
    }

    static final int DIBUTTON_HOCKEYD_MENU() {
        return (int) 436208893L;
    }

    static final int DIHATSWITCH_HOCKEYD_SCROLL() {
        return (int) 436225537L;
    }

    static final int DIBUTTON_HOCKEYD_ZOOM() {
        return (int) 436225030L;
    }

    static final int DIBUTTON_HOCKEYD_STRATEGY() {
        return (int) 436225031L;
    }

    static final int DIBUTTON_HOCKEYD_TIMEOUT() {
        return (int) 436225032L;
    }

    static final int DIBUTTON_HOCKEYD_SUBSTITUTE() {
        return (int) 436225033L;
    }

    static final int DIBUTTON_HOCKEYD_LEFT_LINK() {
        return (int) 436258020L;
    }

    static final int DIBUTTON_HOCKEYD_RIGHT_LINK() {
        return (int) 436258028L;
    }

    static final int DIBUTTON_HOCKEYD_FORWARD_LINK() {
        return (int) 436290784L;
    }

    static final int DIBUTTON_HOCKEYD_BACK_LINK() {
        return (int) 436290792L;
    }

    static final int DIBUTTON_HOCKEYD_DEVICE() {
        return (int) 436225278L;
    }

    static final int DIBUTTON_HOCKEYD_PAUSE() {
        return (int) 436225276L;
    }

    static final int DIVIRTUAL_SPORTS_HOCKEY_GOALIE() {
        return (int) 452984832L;
    }

    static final int DIAXIS_HOCKEYG_LATERAL() {
        return (int) 453018113L;
    }

    static final int DIAXIS_HOCKEYG_MOVE() {
        return (int) 453050882L;
    }

    static final int DIBUTTON_HOCKEYG_PASS() {
        return (int) 452985857L;
    }

    static final int DIBUTTON_HOCKEYG_POKE() {
        return (int) 452985858L;
    }

    static final int DIBUTTON_HOCKEYG_STEAL() {
        return (int) 452985859L;
    }

    static final int DIBUTTON_HOCKEYG_BLOCK() {
        return (int) 452985860L;
    }

    static final int DIBUTTON_HOCKEYG_MENU() {
        return (int) 452986109L;
    }

    static final int DIHATSWITCH_HOCKEYG_SCROLL() {
        return (int) 453002753L;
    }

    static final int DIBUTTON_HOCKEYG_ZOOM() {
        return (int) 453002245L;
    }

    static final int DIBUTTON_HOCKEYG_STRATEGY() {
        return (int) 453002246L;
    }

    static final int DIBUTTON_HOCKEYG_TIMEOUT() {
        return (int) 453002247L;
    }

    static final int DIBUTTON_HOCKEYG_SUBSTITUTE() {
        return (int) 453002248L;
    }

    static final int DIBUTTON_HOCKEYG_LEFT_LINK() {
        return (int) 453035236L;
    }

    static final int DIBUTTON_HOCKEYG_RIGHT_LINK() {
        return (int) 453035244L;
    }

    static final int DIBUTTON_HOCKEYG_FORWARD_LINK() {
        return (int) 453068000L;
    }

    static final int DIBUTTON_HOCKEYG_BACK_LINK() {
        return (int) 453068008L;
    }

    static final int DIBUTTON_HOCKEYG_DEVICE() {
        return (int) 453002494L;
    }

    static final int DIBUTTON_HOCKEYG_PAUSE() {
        return (int) 453002492L;
    }

    static final int DIVIRTUAL_SPORTS_BIKING_MOUNTAIN() {
        return (int) 469762048L;
    }

    static final int DIAXIS_BIKINGM_TURN() {
        return (int) 469795329L;
    }

    static final int DIAXIS_BIKINGM_PEDAL() {
        return (int) 469828098L;
    }

    static final int DIBUTTON_BIKINGM_JUMP() {
        return (int) 469763073L;
    }

    static final int DIBUTTON_BIKINGM_CAMERA() {
        return (int) 469763074L;
    }

    static final int DIBUTTON_BIKINGM_SPECIAL1() {
        return (int) 469763075L;
    }

    static final int DIBUTTON_BIKINGM_SELECT() {
        return (int) 469763076L;
    }

    static final int DIBUTTON_BIKINGM_SPECIAL2() {
        return (int) 469763077L;
    }

    static final int DIBUTTON_BIKINGM_MENU() {
        return (int) 469763325L;
    }

    static final int DIHATSWITCH_BIKINGM_SCROLL() {
        return (int) 469779969L;
    }

    static final int DIBUTTON_BIKINGM_ZOOM() {
        return (int) 469779462L;
    }

    static final int DIAXIS_BIKINGM_BRAKE() {
        return (int) 470041091L;
    }

    static final int DIBUTTON_BIKINGM_LEFT_LINK() {
        return (int) 469812452L;
    }

    static final int DIBUTTON_BIKINGM_RIGHT_LINK() {
        return (int) 469812460L;
    }

    static final int DIBUTTON_BIKINGM_FASTER_LINK() {
        return (int) 469845216L;
    }

    static final int DIBUTTON_BIKINGM_SLOWER_LINK() {
        return (int) 469845224L;
    }

    static final int DIBUTTON_BIKINGM_BRAKE_BUTTON_LINK() {
        return (int) 470041832L;
    }

    static final int DIBUTTON_BIKINGM_DEVICE() {
        return (int) 469779710L;
    }

    static final int DIBUTTON_BIKINGM_PAUSE() {
        return (int) 469779708L;
    }

    static final int DIVIRTUAL_SPORTS_SKIING() {
        return (int) 486539264L;
    }

    static final int DIAXIS_SKIING_TURN() {
        return (int) 486572545L;
    }

    static final int DIAXIS_SKIING_SPEED() {
        return (int) 486605314L;
    }

    static final int DIBUTTON_SKIING_JUMP() {
        return (int) 486540289L;
    }

    static final int DIBUTTON_SKIING_CROUCH() {
        return (int) 486540290L;
    }

    static final int DIBUTTON_SKIING_CAMERA() {
        return (int) 486540291L;
    }

}

