// Generated by jextract

package dev.viskar.lib.dinput8.natives;

class dinput_h_constants_5 extends dinput_h_constants_4 {

    /* package-private */ dinput_h_constants_5() {}
    static final int DIKEYBOARD_INSERT() { return (int)2164262098L; }

    static final int DIKEYBOARD_DELETE() { return (int)2164262099L; }

    static final int DIKEYBOARD_LWIN() { return (int)2164262107L; }

    static final int DIKEYBOARD_RWIN() { return (int)2164262108L; }

    static final int DIKEYBOARD_APPS() { return (int)2164262109L; }

    static final int DIKEYBOARD_POWER() { return (int)2164262110L; }

    static final int DIKEYBOARD_SLEEP() { return (int)2164262111L; }

    static final int DIKEYBOARD_WAKE() { return (int)2164262115L; }

    static final int DIKEYBOARD_WEBSEARCH() { return (int)2164262117L; }

    static final int DIKEYBOARD_WEBFAVORITES() { return (int)2164262118L; }

    static final int DIKEYBOARD_WEBREFRESH() { return (int)2164262119L; }

    static final int DIKEYBOARD_WEBSTOP() { return (int)2164262120L; }

    static final int DIKEYBOARD_WEBFORWARD() { return (int)2164262121L; }

    static final int DIKEYBOARD_WEBBACK() { return (int)2164262122L; }

    static final int DIKEYBOARD_MYCOMPUTER() { return (int)2164262123L; }

    static final int DIKEYBOARD_MAIL() { return (int)2164262124L; }

    static final int DIKEYBOARD_MEDIASELECT() { return (int)2164262125L; }

    static final int DIMOUSE_XAXISAB() { return (int)2181038592L; }

    static final int DIMOUSE_YAXISAB() { return (int)2181038596L; }

    static final int DIMOUSE_XAXIS() { return (int)2181038848L; }

    static final int DIMOUSE_YAXIS() { return (int)2181038852L; }

    static final int DIMOUSE_WHEEL() { return (int)2181038856L; }

    static final int DIMOUSE_BUTTON0() { return (int)2181039116L; }

    static final int DIMOUSE_BUTTON1() { return (int)2181039117L; }

    static final int DIMOUSE_BUTTON2() { return (int)2181039118L; }

    static final int DIMOUSE_BUTTON3() { return (int)2181039119L; }

    static final int DIMOUSE_BUTTON4() { return (int)2181039120L; }

    static final int DIMOUSE_BUTTON5() { return (int)2181039121L; }

    static final int DIMOUSE_BUTTON6() { return (int)2181039122L; }

    static final int DIMOUSE_BUTTON7() { return (int)2181039123L; }

    static final int DIVOICE_CHANNEL1() { return (int)2197816321L; }

    static final int DIVOICE_CHANNEL2() { return (int)2197816322L; }

    static final int DIVOICE_CHANNEL3() { return (int)2197816323L; }

    static final int DIVOICE_CHANNEL4() { return (int)2197816324L; }

    static final int DIVOICE_CHANNEL5() { return (int)2197816325L; }

    static final int DIVOICE_CHANNEL6() { return (int)2197816326L; }

    static final int DIVOICE_CHANNEL7() { return (int)2197816327L; }

    static final int DIVOICE_CHANNEL8() { return (int)2197816328L; }

    static final int DIVOICE_TEAM() { return (int)2197816329L; }

    static final int DIVOICE_ALL() { return (int)2197816330L; }

    static final int DIVOICE_RECORDMUTE() { return (int)2197816331L; }

    static final int DIVOICE_PLAYBACKMUTE() { return (int)2197816332L; }

    static final int DIVOICE_TRANSMIT() { return (int)2197816333L; }

    static final int DIVOICE_VOICECOMMAND() { return (int)2197816336L; }

    static final int DIAXIS_ANY_X_1() { return (int)4278239745L; }

    static final int DIAXIS_ANY_X_2() { return (int)4278239746L; }

    static final int DIAXIS_ANY_Y_1() { return (int)4278272513L; }

    static final int DIAXIS_ANY_Y_2() { return (int)4278272514L; }

    static final int DIAXIS_ANY_Z_1() { return (int)4278305281L; }

    static final int DIAXIS_ANY_Z_2() { return (int)4278305282L; }

    static final int DIAXIS_ANY_R_1() { return (int)4278338049L; }

    static final int DIAXIS_ANY_R_2() { return (int)4278338050L; }

    static final int DIAXIS_ANY_U_1() { return (int)4278370817L; }

    static final int DIAXIS_ANY_U_2() { return (int)4278370818L; }

    static final int DIAXIS_ANY_V_1() { return (int)4278403585L; }

    static final int DIAXIS_ANY_V_2() { return (int)4278403586L; }

    static final int DIAXIS_ANY_A_1() { return (int)4278436353L; }

    static final int DIAXIS_ANY_A_2() { return (int)4278436354L; }

    static final int DIAXIS_ANY_B_1() { return (int)4278469121L; }

    static final int DIAXIS_ANY_B_2() { return (int)4278469122L; }

    static final int DIAXIS_ANY_C_1() { return (int)4278501889L; }

    static final int DIAXIS_ANY_C_2() { return (int)4278501890L; }

    static final int DIAXIS_ANY_S_1() { return (int)4278534657L; }

    static final int DIAXIS_ANY_S_2() { return (int)4278534658L; }

    static final int DIAXIS_ANY_1() { return (int)4278206977L; }

    static final int DIAXIS_ANY_2() { return (int)4278206978L; }

    static final int DIAXIS_ANY_3() { return (int)4278206979L; }

    static final int DIAXIS_ANY_4() { return (int)4278206980L; }

    static final int DIPOV_ANY_1() { return (int)4278208001L; }

    static final int DIPOV_ANY_2() { return (int)4278208002L; }

    static final int DIPOV_ANY_3() { return (int)4278208003L; }

    static final int DIPOV_ANY_4() { return (int)4278208004L; }

    static final int JOY_PASSDRIVERDATA() { return (int)268435456L; }

    static final int JOY_HWS_ISHEADTRACKER() { return (int)33554432L; }

    static final int JOY_HWS_ISGAMEPORTDRIVER() { return (int)67108864L; }

    static final int JOY_HWS_ISANALOGPORTDRIVER() { return (int)134217728L; }

    static final int JOY_HWS_AUTOLOAD() { return (int)268435456L; }

    static final int JOY_HWS_NODEVNODE() { return (int)536870912L; }

    static final int JOY_HWS_ISGAMEPORTBUS() { return (int)2147483648L; }

    static final int JOY_HWS_GAMEPORTBUSBUSY() { return (int)1L; }

    static final int JOY_US_VOLATILE() { return (int)8L; }

}

